name: Build and Release

on:
  push:
    tags:
      - 'v*'   # e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.10'

      # 3️⃣ Install dependencies (in ./web_app)
      - name: Install dependencies
        working-directory: ./web_app
        run: npm ci

      # 4️⃣ Build app (in ./web_app)
      - name: Build app
        working-directory: ./web_app
        run: npm run build-local-chat linux

      # 5️⃣ Create GitHub release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6️⃣ Upload build output as release asset
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

